### ISSUE TITLE
Issue with Running client behind NAT - Apache Ignite

### ISSUE THREAD

**Issue by VMahipalReddy** [apache/ignite#10599]
Hi Team,

We have an Ignite cluster(2.14) running in a private network, and we are trying to load data into the cluster from outside.

Using Thick client:

- We are trying run spark data load job from OracleDataCloud Dataflow(k8s architecture)
- But client is not able to join the cluster even with <property name="forceClientToServerConnections" value="true"/>

Using Thin client:

- When we try to load data, we see memory spikes in one/few nodes only, with partition awareness enabled
- Data is not getting distributed. PFA
<img width="1716" alt="ignite-data-distribution-issue" src="https://user-images.githubusercontent.com/37264160/225572809-46ec1631-ea8d-4ddb-a099-e8773aff18d0.png">

Could you please suggest a solution.

**Comment by shishkovilja** [comment]
Hi @VMahipalReddy,

For thick client you can try this: [Running Client Nodes Behind NAT](https://ignite.apache.org/docs/latest/clustering/running-client-nodes-behind-nat).

For thin client, there are some notable points:
1. Some requests, such as explicit transactions does not support partition awareness.
1. All operations, which does not support partition awareness performed operations through the node which it is connected to. Since 2.12 thin client connects to the first address from specified addresses list, so if you run many clients with the same addresses list, all of them will be connected to a single node.  As a workaround you can perform manual shuffling of addresses in your code. In 2.15 connection balancing will be introduced: [IGNITE-18637](https://issues.apache.org/jira/browse/IGNITE-18637)

> Data is not getting distributed

Which metric is displayed on the attached picture?
